-- MySQL Script generated by MySQL Workbench
-- Thu Oct 20 11:35:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema secretCellar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `secretCellar` ;

-- -----------------------------------------------------
-- Schema secretCellar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `secretCellar` DEFAULT CHARACTER SET utf8 ;
USE `secretCellar` ;

-- -----------------------------------------------------
-- Table `secretCellar`.`appellation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretCellar`.`appellation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secretCellar`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretCellar`.`color` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secretCellar`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretCellar`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secretCellar`.`domaine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretCellar`.`domaine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secretCellar`.`grapevariety`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretCellar`.`grapevariety` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secretCellar`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretCellar`.`region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secretCellar`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretCellar`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secretCellar`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretCellar`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role_id` INT NOT NULL,
  `avatar` BLOB NULL,
  `dateOfBirth` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `secretCellar`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secretCellar`.`user_has_wine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretCellar`.`user_has_wine` (
  `user_id` INT NOT NULL,
  `wine_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `wine_id`),
  INDEX `fk_user_has_wine_wine1_idx` (`wine_id` ASC) VISIBLE,
  INDEX `fk_user_has_wine_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_wine_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `secretCellar`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_wine_wine1`
    FOREIGN KEY (`wine_id`)
    REFERENCES `secretCellar`.`wine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secretCellar`.`vintage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretCellar`.`vintage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secretCellar`.`wine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretCellar`.`wine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` LONGTEXT NULL,
  `comment` LONGTEXT NULL,
  `rank` FLOAT NULL,
  `price` FLOAT NULL,
  `stock` INT NULL,
  `value` FLOAT NULL,
  `cellarLocation` VARCHAR(45) NULL,
  `picture` BLOB NULL,
  `ageingTime` INT NULL,
  `color_id` INT NOT NULL,
  `country_id` INT NOT NULL,
  `vintage_id` INT NOT NULL,
  `region_id` INT NOT NULL,
  `domaine_id` INT NOT NULL,
  `grapevariety_id` INT NOT NULL,
  `appellation_id` INT NOT NULL,
  `purchaseDate` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_wine_color1_idx` (`color_id` ASC) VISIBLE,
  INDEX `fk_wine_country1_idx` (`country_id` ASC) VISIBLE,
  INDEX `fk_wine_vintage1_idx` (`vintage_id` ASC) VISIBLE,
  INDEX `fk_wine_region1_idx` (`region_id` ASC) VISIBLE,
  INDEX `fk_wine_domaine1_idx` (`domaine_id` ASC) VISIBLE,
  INDEX `fk_wine_grapevariety1_idx` (`grapevariety_id` ASC) VISIBLE,
  INDEX `fk_wine_appellation1_idx` (`appellation_id` ASC) VISIBLE,
  CONSTRAINT `fk_wine_color1`
    FOREIGN KEY (`color_id`)
    REFERENCES `secretCellar`.`color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wine_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `secretCellar`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wine_vintage1`
    FOREIGN KEY (`vintage_id`)
    REFERENCES `secretCellar`.`vintage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wine_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `secretCellar`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wine_domaine1`
    FOREIGN KEY (`domaine_id`)
    REFERENCES `secretCellar`.`domaine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wine_grapevariety1`
    FOREIGN KEY (`grapevariety_id`)
    REFERENCES `secretCellar`.`grapevariety` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wine_appellation1`
    FOREIGN KEY (`appellation_id`)
    REFERENCES `secretCellar`.`appellation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secretCellar`.`wine_has_winePairing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretCellar`.`wine_has_winePairing` (
  `wine_id` INT NOT NULL,
  `winePairing_id` INT NOT NULL,
  PRIMARY KEY (`wine_id`, `winePairing_id`),
  INDEX `fk_wine_has_winePairing_winePairing1_idx` (`winePairing_id` ASC) VISIBLE,
  INDEX `fk_wine_has_winePairing_wine1_idx` (`wine_id` ASC) VISIBLE,
  CONSTRAINT `fk_wine_has_winePairing_wine1`
    FOREIGN KEY (`wine_id`)
    REFERENCES `secretCellar`.`wine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wine_has_winePairing_winePairing1`
    FOREIGN KEY (`winePairing_id`)
    REFERENCES `secretCellar`.`winePairing` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secretCellar`.`winePairing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretCellar`.`winePairing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
